// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7D_fUQELZ1qllIAjMwu2Glh1BKkQ0X8k',
    appId: '1:426324191741:android:b1f9f90b64e9fce10e1194',
    messagingSenderId: '426324191741',
    projectId: 'to-do-1f3aa',
    databaseURL: 'https://to-do-1f3aa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'to-do-1f3aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeE-h7t-o_2E03lA9xzMDOs1neDDaV9P0',
    appId: '1:426324191741:ios:d9ae4ebf78d126f00e1194',
    messagingSenderId: '426324191741',
    projectId: 'to-do-1f3aa',
    databaseURL: 'https://to-do-1f3aa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'to-do-1f3aa.appspot.com',
    iosClientId: '426324191741-o01v0j36uab6c9gv1b4p27b485high8h.apps.googleusercontent.com',
    iosBundleId: 'com.example.xyz',
  );
}
